### ISSUE TITLE
Missing brand_id on App resource

### ISSUE THREAD

**Issue by richet** [onelogin/terraform-provider-onelogin#34]
The OneLogin App resource now supports a `brand_id` attribute that can be used to control the branding of the login page for the app. 

https://developers.onelogin.com/api-docs/2/apps/app-resource

Can we get this added to the App resource in the provider?

**Comment by dcaponi** [comment]
According to that documentation, it looks like one should be able to set it and its optional. I'll add that 👍

**Comment by richet** [comment]
Yes the default is null and it can be set on create or update.

Awesome. Thanks!

**Comment by dcaponi** [comment]
Should be good to go as of v0.1.5
