### ISSUE TITLE
Data Resources

### ISSUE THREAD

**Issue by jaydeland** [onelogin/terraform-provider-onelogin#38]
Can we get a data resource object for users? I see there is already a readUser function
https://github.com/onelogin/terraform-provider-onelogin/blob/86a146cbd71eba226bfa2aa7cccbfc34dde0b070/onelogin/resource_onelogin_users.go#L99

**Comment by ZsoltPath** [comment]
I've just noticed this is missing. Very sad indeed.

**Comment by ZsoltPath** [comment]
https://github.com/onelogin/terraform-provider-onelogin/pull/48

**Comment by dcaponi** [comment]
@jaydeland @ZsoltPath I went and merged that PR Thanks for the input @ZsoltPath.
