### ISSUE TITLE
Support for Apple Silicon?

### ISSUE THREAD

**Issue by lighterless** [onelogin/terraform-provider-onelogin#49]
Any chance we can get an updated build for Apple Silicon (darwin_arm64)?

```
Initializing provider plugins...
- Finding onelogin/onelogin versions matching "0.1.14"...
╷
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/onelogin/onelogin v0.1.14 does not have a package available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may
│ have different platforms supported.
```

**Comment by dcaponi** [comment]
hey @lighterless my suspicion is that the pipeline just needs to build with the latest version of Go. I plan to update the goreleaser config to use go v1.16. Is that a version you're running on M1 (sadly I lack a development machine to know for myself)

**Comment by lighterless** [comment]
hey @dcaponi yes I'm running go v.1.16.3 on my M1 mac.

**Comment by dcaponi** [comment]
thats what I thought. lemme update the go version in the pipeline. should be ready to try by end of day

**Comment by dcaponi** [comment]
@lighterless my understanding of how goreleaser does this is if you build in an env where the go version is 1.16 or higher, the default for apple silicon changes to darwin/arm64 https://goreleaser.com/deprecations/#builds-for-darwinarm64 in addition to darwin/amd64. 

So I updated the go version and that M1 support should work in [v0.1.18](https://github.com/onelogin/terraform-provider-onelogin/releases/tag/v0.1.18)

Please let me know if that works.
