### ISSUE TITLE
OIDC App Missing post_logout_redirect_uri

### ISSUE THREAD

**Issue by akozmic-prisidio** [onelogin/terraform-provider-onelogin#50]
looks like there is no option for post_logout_redirect_uri on the OIDC App
https://github.com/onelogin/terraform-provider-onelogin/blob/develop/docs/resources/onelogin_oidc_app.md

This caused me to accidentally blow away all our values on a dev server today.  I noticed the OneLogin SDK for Go also doesn't support it yet so the SDK would likely need to be updated as well. https://github.com/onelogin/onelogin-go-sdk/blob/develop/pkg/services/apps/model.go#L61

**Comment by akozmic-prisidio** [comment]
Thanks @dcaponi   it looks like its there.  Is there a reason it's not in the "configuration" section?  Looks like its in "parameters" 
see: https://github.com/onelogin/terraform-provider-onelogin/blob/develop/docs/resources/onelogin_oidc_app.md.  

I see further down in documentation that it says it's in "configuration".   Not sure if this is an issue with the code or just an issue with the documentation readme.

**Comment by dcaponi** [comment]
oh this is my bad. looks like the example is wrong. It should be in the `configuration` section and it is correctly placed in the resource https://github.com/onelogin/terraform-provider-onelogin/blob/develop/ol_schema/app/configuration/configuration.go#L55
and
https://github.com/onelogin/terraform-provider-onelogin/blob/develop/ol_schema/app/configuration/configuration.go#L123
