### ISSUE TITLE
Documentation indentation issues

### ISSUE THREAD

**Issue by haavardw** [onelogin/terraform-provider-onelogin#52]
Several places in the documentation seem to have annoying (for readability) whitespace issues.
Examples:
- https://registry.terraform.io/providers/onelogin/onelogin/latest/docs/resources/onelogin_oidc_app
  2 vs 4 vs tab indentation? See the name and visible argument in the first example.
- https://registry.terraform.io/providers/onelogin/onelogin/latest/docs/resources/onelogin_app
  2 vs 4 spaces indentation? See the parameters block in the first example.

**Comment by dcaponi** [comment]
@haavardw Thanks for bringing this up! I will fix in the next feature release. Here's the current status. I need to finish up another piece of this but it should be out by end of this week. https://github.com/onelogin/terraform-provider-onelogin/pull/53
