### ISSUE TITLE
creating an app by terraform

### ISSUE THREAD

**Issue by aberyo0801** [onelogin/terraform-provider-onelogin#58]
When I create an app using terraform, the credential setting is "Configured by end-users" by default as shown in the attached picture.

If I want to change the credential setting to "Configured by admins and shared by all users" and create an app, how do I set the Argument Reference described in the terraform documentation?

[The documentation about Argument reference](https://registry.terraform.io/providers/onelogin/onelogin/latest/docs/resources/onelogin_app)

<img width="433" alt="credentials setting" src="https://user-images.githubusercontent.com/72190144/119799754-5966e280-bf17-11eb-9d44-2c18b160d56b.png">

**Comment by dcaponi** [comment]
@aberyo0801 is this a SAML or OIDC app? Some of those fields are only valid on a per app type basis and sadly, some of those specialized fields are not documented. Can you give me some more info about the app you're trying to create so I can try to find the name of the field and add it. Thanks 😄
