### ISSUE TITLE
saml_app sso certificate attribute

### ISSUE THREAD

**Issue by rjhornsby** [onelogin/terraform-provider-onelogin#81]
The [onelogin_saml_app](https://registry.terraform.io/providers/onelogin/onelogin/latest/docs/resources/onelogin_saml_app) provider [docs](https://registry.terraform.io/providers/onelogin/onelogin/latest/docs/resources/onelogin_saml_app#certificate) indicate that the SAML certificate should be an attribute found at `onelogin_saml_apps.myapp.sso.certificate`

Quoting from the doc -
> * [sso](https://registry.terraform.io/providers/onelogin/onelogin/latest/docs/resources/onelogin_saml_app#sso) - The attributes included in the sso section are determined by the type of app. sso attributes are read only.
> ...
>   * certificate - The SSO certificate generated by OneLogin.

However, looking at the provider resource code, it appears that the certificate needs to be accessed at the parent level and through the `value` attribute, like so: `onelogin_saml_apps.myapp.certificate.value`

https://github.com/onelogin/terraform-provider-onelogin/blob/35a437fca82b7fdef6029296aa81cea21d933236/onelogin/resource_onelogin_saml_apps.go#L110

https://github.com/onelogin/terraform-provider-onelogin/blob/35a437fca82b7fdef6029296aa81cea21d933236/ol_schema/app/sso/sso.go#L16-L21

**Comment by Jmfwolf** [comment]
We are in the process of standardizing our SDKs by using OpenAPI specifications.
I have an OpenAPI generated terraform-provider-onelogin in prerelease if you would like t try it out.
https://github.com/onelogin/terraform-provider-onelogin/tree/openapi

**Comment by Jmfwolf** [comment]
This feature request will be placed as backlog given the prioritization of your other request
