### ISSUE TITLE
Ability to manage groups through the provider

### ISSUE THREAD

**Issue by kda-jt** [onelogin/terraform-provider-onelogin#89]
Hi,

I couldn't find any mention of this elsewhere, so I'm opening an issue.

The provider currently does not have to capability to manage [OneLogin groups](https://developers.onelogin.com/api-docs/1/groups/get-groups).

Is this planned by any chance?

**Comment by ebarti** [comment]
This provider looks unmaintained. I created a maintained version [here](https://github.com/Glovo/terraform-provider-onelogin) with a few bugfixes and am planning on releaseing some features (related to auth servers - scopes, claims and client apps)

**Comment by Jmfwolf** [comment]
Hey @kda-jt,

Would you help me out and clarify which part of the Onelogin group you are seeking to manage through the provider?

Users are able to be added and removed from groups through the user endpoint [OneLogin groups](https://developers.onelogin.com/api-docs/1/groups/get-groups#:~:text=To%20find%20out%20which%20group%20a%20user%20belongs%20to%2C%20use%20the%20Get%20User%20by%20ID%C2%A0API.)

With some clarification we are more than willing to fix any issues and begin investigating

**Comment by kda-jt** [comment]
@ebarti 

> This provider looks unmaintained.

It sure looks like it.

> I created a maintained version [here](https://github.com/Glovo/terraform-provider-onelogin) with a few bugfixes and am planning on releaseing some features

Kudos to you, looking forward to seeing the new goodies

**Comment by Subterrane** [comment]
> 
>     This provider looks unmaintained.
> 
> It sure looks like it.

@Jmfwolf will be maintaining this repo.

**Comment by Jmfwolf** [comment]
We are in the process of standardizing our SDKs by using OpenAPI specifications.
I have an OpenAPI generated terraform-provider-onelogin in prerelease if you would like t try it out.
https://github.com/onelogin/terraform-provider-onelogin/tree/openapi

**Comment by kda-jt** [comment]
@Jmfwolf I'm no longer a OneLogin user.
I'll keep the issue open as I do believe this is an interesting feature.
