### ISSUE TITLE
Which connectors are supported?

### ISSUE THREAD

**Issue by mikkoc** [onelogin/terraform-provider-onelogin#9]
Is there a list of supported `connector_id`s?

I tried to create a new Splunk connector (`connector_id=229`), SAML 2.0 based. But got the following error:

```
Error: error: context: [ol http service], error_message: [{"message":"Unknown parameter on configuration section: provider_arn","name":"BadRequestError","statusCode":400}]
```

```
resource onelogin_saml_apps saml {
  connector_id = 229
  name         = "Terraform Test SAML App"
  description  = "SAML"

  configuration {
    signature_algorithm = "SHA-1"
  }
}
```

I understand this might be nowhere near to be ready, so I understand if you prefer people not to open issues yet.

We're quite keen to follow the development of this provider and can do beta testing if you need. We have a lot of manual OL apps we're keen to import in TF.

Thanks

**Comment by dcaponi** [comment]
I made a small release you can try (also in master) that removes the field `provider_arn`. Note, you won't be able to set this on the AWS app that uses it via Terraform (you'll still be able to use the UI) but that should get you over the hump. I tried it with this config and it worked for me

```
provider onelogin {
	alias = "onelogin"
}
resource onelogin_saml_apps saml {
  connector_id = 55785
  name         = "Terraform Test SAML App"
  description  = "SAML"

  configuration {
    signature_algorithm = "SHA-1"
  }
}
```

Please, if this unblocks you close the issue. If I don't hear back in about 3 business days I'll close it.

**Comment by mikkoc** [comment]
Thanks @dcaponi I'll try that early next week!

**Comment by mikkoc** [comment]
That worked, thanks, closing this.
