### ISSUE TITLE
Allow increasing the timeout

### ISSUE THREAD

**Issue by orf** [onelogin/terraform-provider-onelogin#91]
Hello,
We are continually seeing this error when planning our terraform resources:

```
Error: App does not exist request error: context: ol http service, error_message: Post "https://api.us.onelogin.com/auth/oauth2/v2/token": EOF
```

On these errors, which happen frequently, there seems to be no automatic retrying. It would be great to be able to configure this: https://github.com/onelogin/terraform-provider-onelogin/blob/develop/onelogin/provider.go#L73

**Comment by Jmfwolf** [comment]
We are in the process of standardizing our SDKs by using OpenAPI specifications.
I have an OpenAPI generated terraform-provider-onelogin in prerelease if you would like t try it out.
https://github.com/onelogin/terraform-provider-onelogin/tree/openapi

**Comment by orf** [comment]
Hey, we are switching to Otka, which has a lot better functioning provider.

However this issue is still valid, and doesn’t really have anything to do with openapi. Feel free to close it when/if timeouts are implemented. 

IMO, implementing timeouts should take about 30 minutes end-to-end to ship.
